version: "3"
services:
  app:
    build: .
    image: ${ORGANIZATION}/${CONTAINER}:${BUILD_TAG}
    container_name: ${CONTAINER}
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - "./src:/opt/src"
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
